In [1]:
#データを開ける
#格納されている形を確かめる
#Dictionaryからlist

NameError: name 'データを開ける' is not defined

In [36]:
import pickle as pkl
import numpy as np

In [37]:
with open ('../data/assignment1/cat_data.pkl', mode="rb") as f:
    cat_data=pickle.load(f)

In [38]:
print(cat_data)

{'train': {'cat': array([[[[ 82,  71,  68],
         [ 89,  83,  83],
         [100,  98, 104],
         ...,
         [131, 132, 137],
         [126, 124, 124],
         [105,  97,  95]],

        [[ 95,  91,  97],
         [104, 104, 113],
         [110, 115, 126],
         ...,
         [135, 134, 135],
         [127, 122, 119],
         [111, 105, 103]],

        [[ 94,  85,  83],
         [ 97,  89,  90],
         [110, 109, 115],
         ...,
         [136, 134, 131],
         [127, 120, 117],
         [116, 108, 104]],

        ...,

        [[ 96, 116, 131],
         [ 97, 115, 130],
         [103, 123, 139],
         ...,
         [152, 155, 157],
         [146, 149, 152],
         [130, 133, 134]],

        [[ 90, 108, 123],
         [ 92, 108, 121],
         [100, 119, 134],
         ...,
         [150, 152, 155],
         [144, 146, 147],
         [134, 135, 134]],

        [[ 86, 102, 116],
         [ 87, 103, 115],
         [ 94, 114, 127],
         ...,
         [154, 1

In [39]:
list(cat_data)

['train', 'test']

In [40]:
list(cat_data['train'])

['cat', 'no_cat']

In [41]:
list(cat_data['test'])

['cat', 'no_cat']

In [42]:
list(cat_data['train']['cat'])

[array([[[ 82,  71,  68],
         [ 89,  83,  83],
         [100,  98, 104],
         ...,
         [131, 132, 137],
         [126, 124, 124],
         [105,  97,  95]],
 
        [[ 95,  91,  97],
         [104, 104, 113],
         [110, 115, 126],
         ...,
         [135, 134, 135],
         [127, 122, 119],
         [111, 105, 103]],
 
        [[ 94,  85,  83],
         [ 97,  89,  90],
         [110, 109, 115],
         ...,
         [136, 134, 131],
         [127, 120, 117],
         [116, 108, 104]],
 
        ...,
 
        [[ 96, 116, 131],
         [ 97, 115, 130],
         [103, 123, 139],
         ...,
         [152, 155, 157],
         [146, 149, 152],
         [130, 133, 134]],
 
        [[ 90, 108, 123],
         [ 92, 108, 121],
         [100, 119, 134],
         ...,
         [150, 152, 155],
         [144, 146, 147],
         [134, 135, 134]],
 
        [[ 86, 102, 116],
         [ 87, 103, 115],
         [ 94, 114, 127],
         ...,
         [154, 156, 160],
  

In [53]:
cat_data['train']['cat'].shape

(72, 64, 64, 3)

In [54]:
cat_data['train']['no_cat'].shape

(137, 64, 64, 3)

In [56]:
cat_data['test']['cat'].shape

(33, 64, 64, 3)

In [57]:
cat_data['test']['no_cat'].shape

(17, 64, 64, 3)

In [47]:
cat_data['train']['cat'][0]

array([[[ 82,  71,  68],
        [ 89,  83,  83],
        [100,  98, 104],
        ...,
        [131, 132, 137],
        [126, 124, 124],
        [105,  97,  95]],

       [[ 95,  91,  97],
        [104, 104, 113],
        [110, 115, 126],
        ...,
        [135, 134, 135],
        [127, 122, 119],
        [111, 105, 103]],

       [[ 94,  85,  83],
        [ 97,  89,  90],
        [110, 109, 115],
        ...,
        [136, 134, 131],
        [127, 120, 117],
        [116, 108, 104]],

       ...,

       [[ 96, 116, 131],
        [ 97, 115, 130],
        [103, 123, 139],
        ...,
        [152, 155, 157],
        [146, 149, 152],
        [130, 133, 134]],

       [[ 90, 108, 123],
        [ 92, 108, 121],
        [100, 119, 134],
        ...,
        [150, 152, 155],
        [144, 146, 147],
        [134, 135, 134]],

       [[ 86, 102, 116],
        [ 87, 103, 115],
        [ 94, 114, 127],
        ...,
        [154, 156, 160],
        [146, 148, 152],
        [138, 141, 142]]

In [48]:
cat_data['train']['cat'][0][0]

array([[ 82,  71,  68],
       [ 89,  83,  83],
       [100,  98, 104],
       [106, 105, 116],
       [118, 123, 135],
       [121, 124, 133],
       [119, 119, 127],
       [133, 135, 144],
       [132, 132, 135],
       [130, 129, 130],
       [136, 133, 135],
       [128, 120, 119],
       [129, 121, 119],
       [131, 123, 121],
       [135, 127, 123],
       [126, 117, 111],
       [135, 130, 129],
       [135, 125, 121],
       [130, 118, 110],
       [ 99,  82,  73],
       [109,  94,  87],
       [130, 118, 111],
       [135, 120, 108],
       [128, 107,  88],
       [124,  98,  77],
       [130, 108,  89],
       [133, 115,  95],
       [100,  78,  60],
       [ 92,  68,  50],
       [120,  99,  84],
       [141, 128, 122],
       [152, 143, 137],
       [154, 143, 135],
       [160, 152, 150],
       [156, 149, 146],
       [149, 141, 142],
       [148, 143, 149],
       [149, 146, 156],
       [154, 157, 173],
       [155, 164, 183],
       [157, 168, 185],
       [158, 174

In [49]:
cat_data['train']['cat'][0][0][0]

array([82, 71, 68], dtype=uint8)

In [60]:
#最終的に目標にする形：list([r1,g1,b1,...,r,g,b],cat)

In [78]:
#一枚目の画像のピクセルを一つにまとめる
train_cat_zero = cat_data['train']['cat'][0]
print(train_cat_zero)

[[[ 82  71  68]
  [ 89  83  83]
  [100  98 104]
  ...
  [131 132 137]
  [126 124 124]
  [105  97  95]]

 [[ 95  91  97]
  [104 104 113]
  [110 115 126]
  ...
  [135 134 135]
  [127 122 119]
  [111 105 103]]

 [[ 94  85  83]
  [ 97  89  90]
  [110 109 115]
  ...
  [136 134 131]
  [127 120 117]
  [116 108 104]]

 ...

 [[ 96 116 131]
  [ 97 115 130]
  [103 123 139]
  ...
  [152 155 157]
  [146 149 152]
  [130 133 134]]

 [[ 90 108 123]
  [ 92 108 121]
  [100 119 134]
  ...
  [150 152 155]
  [144 146 147]
  [134 135 134]]

 [[ 86 102 116]
  [ 87 103 115]
  [ 94 114 127]
  ...
  [154 156 160]
  [146 148 152]
  [138 141 142]]]


In [95]:
train_cat_zero.ravel()

array([ 82,  71,  68, ..., 138, 141, 142], dtype=uint8)

In [147]:
train = []
for i,j in cat_data['train'].items():
    for r in j:
        train.append((r.ravel()/255, 1 if i=='cat' else 0))

# i: cat or not_cat
# j: image
# r: pixels in 64*64「この8ビット画像では、濃淡を2の8乗＝256階調まで表すことができます。画素値0が黒、画素値255が白になります。」
#(())にしないと一つだと認識されないからerrorを吐く

In [140]:
train

[array([0.32156863, 0.27843137, 0.26666667, ..., 0.54117647, 0.55294118,
        0.55686275]),
 1,
 array([0.0745098 , 0.08627451, 0.00784314, ..., 0.02745098, 0.03137255,
        0.01568627]),
 1,
 array([0.01568627, 0.02352941, 0.01176471, ..., 0.4745098 , 0.5372549 ,
        0.57254902]),
 1,
 array([0.06666667, 0.0627451 , 0.10980392, ..., 0.22352941, 0.11764706,
        0.19607843]),
 1,
 array([0.28235294, 0.29411765, 0.29019608, ..., 0.21176471, 0.2       ,
        0.18039216]),
 1,
 array([0.00784314, 0.00784314, 0.00784314, ..., 0.08627451, 0.0745098 ,
        0.03137255]),
 1,
 array([0.47843137, 0.40784314, 0.25490196, ..., 0.57254902, 0.48627451,
        0.50196078]),
 1,
 array([0.05882353, 0.05882353, 0.01960784, ..., 0.        , 0.        ,
        0.        ]),
 1,
 array([0.14117647, 0.14117647, 0.10196078, ..., 0.59607843, 0.64705882,
        0.63137255]),
 1,
 array([0.70588235, 0.70980392, 0.68627451, ..., 0.21960784, 0.0745098 ,
        0.09411765]),
 1,
 array([0.